/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingGoalRouteImport } from './routes/onboarding/goal'
import { Route as OnboardingInterestsRouteImport } from './routes/onboarding/interests'
import { Route as OnboardingOfferRouteImport } from './routes/onboarding/offer'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as ReaderIndexRouteImport } from './routes/reader/index'
import { Route as ReaderBookIdRouteImport } from './routes/reader/$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/onboarding/goal',
  path: '/onboarding/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInterestsRoute = OnboardingInterestsRouteImport.update({
  id: '/onboarding/interests',
  path: '/onboarding/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOfferRoute = OnboardingOfferRouteImport.update({
  id: '/onboarding/offer',
  path: '/onboarding/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderIndexRoute = ReaderIndexRouteImport.update({
  id: '/reader/',
  path: '/reader/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderBookIdRoute = ReaderBookIdRouteImport.update({
  id: '/reader/$bookId',
  path: '/reader/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/signup': typeof SignupRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/offer': typeof OnboardingOfferRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/reader/': typeof ReaderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/signup': typeof SignupRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/offer': typeof OnboardingOfferRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/reader': typeof ReaderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/signup': typeof SignupRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/offer': typeof OnboardingOfferRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/reader/': typeof ReaderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/explore'
    | '/library'
    | '/login'
    | '/plans'
    | '/signup'
    | '/onboarding/goal'
    | '/onboarding/interests'
    | '/onboarding/offer'
    | '/onboarding/welcome'
    | '/reader/$bookId'
    | '/reader/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/explore'
    | '/library'
    | '/login'
    | '/plans'
    | '/signup'
    | '/onboarding/goal'
    | '/onboarding/interests'
    | '/onboarding/offer'
    | '/onboarding/welcome'
    | '/reader/$bookId'
    | '/reader'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/explore'
    | '/library'
    | '/login'
    | '/plans'
    | '/signup'
    | '/onboarding/goal'
    | '/onboarding/interests'
    | '/onboarding/offer'
    | '/onboarding/welcome'
    | '/reader/$bookId'
    | '/reader/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  SignupRoute: typeof SignupRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingInterestsRoute: typeof OnboardingInterestsRoute
  OnboardingOfferRoute: typeof OnboardingOfferRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  ReaderBookIdRoute: typeof ReaderBookIdRoute
  ReaderIndexRoute: typeof ReaderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/onboarding/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/interests': {
      id: '/onboarding/interests'
      path: '/onboarding/interests'
      fullPath: '/onboarding/interests'
      preLoaderRoute: typeof OnboardingInterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/offer': {
      id: '/onboarding/offer'
      path: '/onboarding/offer'
      fullPath: '/onboarding/offer'
      preLoaderRoute: typeof OnboardingOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/': {
      id: '/reader/'
      path: '/reader'
      fullPath: '/reader/'
      preLoaderRoute: typeof ReaderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$bookId': {
      id: '/reader/$bookId'
      path: '/reader/$bookId'
      fullPath: '/reader/$bookId'
      preLoaderRoute: typeof ReaderBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  SignupRoute: SignupRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingInterestsRoute: OnboardingInterestsRoute,
  OnboardingOfferRoute: OnboardingOfferRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  ReaderBookIdRoute: ReaderBookIdRoute,
  ReaderIndexRoute: ReaderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
